# -*- coding: utf-8 -*-
"""Traditional ML models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VIz4f73Q31tiLSlaXvHKK93s1ZTM98lX
"""

# ============================================================
# FAKE NEWS DETECTION - Traditional ML Models
# Using pre-computed TF-IDF features
# ============================================================

# STEP 1: Mount Drive
from google.colab import drive
drive.mount('/content/drive')

# STEP 2: Install XGBoost
!pip install xgboost -q

# STEP 3: Imports
import numpy as np
import pandas as pd
import scipy.sparse as sp
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier
from sklearn.metrics import (accuracy_score, precision_score,
                             recall_score, f1_score,
                             classification_report,
                             confusion_matrix, roc_auc_score)
import warnings
warnings.filterwarnings('ignore')

# STEP 4: Load pre-computed TF-IDF features + labels
TFIDF_PATH = '/content/drive/MyDrive/comparative-analysis-main/datasetnew/for if-idf/'
CSV_PATH   = '/content/drive/MyDrive/comparative-analysis-main/datasetnew/'

# Features
X_train = sp.load_npz(TFIDF_PATH + 'X_train_tfidf.npz')
X_test  = sp.load_npz(TFIDF_PATH + 'X_test_tfidf.npz')
X_val   = sp.load_npz(TFIDF_PATH + 'X_val_tfidf.npz')

# Labels
y_train = pd.read_csv(CSV_PATH + 'train_binary.csv')['label'].values
y_test  = pd.read_csv(CSV_PATH + 'test_binary.csv')['label'].values
y_val   = pd.read_csv(CSV_PATH + 'val_binary.csv')['label'].values

print("X_train:", X_train.shape, "| y_train:", y_train.shape)
print("X_test :", X_test.shape,  "| y_test :", y_test.shape)
print("X_val  :", X_val.shape,   "| y_val  :", y_val.shape)
print("\nLabel distribution (test):")
print(pd.Series(y_test).value_counts().rename({0:'Real', 1:'Fake'}))

# STEP 5: Define all models
models = {
    'Naive Bayes'        : MultinomialNB(),
    'Logistic Regression': LogisticRegression(max_iter=1000, C=1.0),
    'SVM (LinearSVC)'    : LinearSVC(max_iter=2000, C=1.0),
    'Random Forest'      : RandomForestClassifier(n_estimators=100,
                                                   random_state=42,
                                                   n_jobs=-1),
    'Decision Tree'      : DecisionTreeClassifier(random_state=42),
    'XGBoost'            : XGBClassifier(eval_metric='logloss',
                                         random_state=42,
                                         n_jobs=-1)
}

# STEP 6: Train and evaluate all models
results = []

for name, model in models.items():
    print(f"\n{'='*50}")
    print(f"Training: {name}")

    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    acc  = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred, average='weighted', zero_division=0)
    rec  = recall_score(y_test, y_pred, average='weighted', zero_division=0)
    f1   = f1_score(y_test, y_pred, average='weighted', zero_division=0)

    # AUC-ROC
    try:
        if hasattr(model, 'predict_proba'):
            y_prob = model.predict_proba(X_test)[:, 1]
        else:
            y_prob = model.decision_function(X_test)
        auc = roc_auc_score(y_test, y_prob)
    except:
        auc = None

    results.append({
        'Model'    : name,
        'Accuracy' : round(acc * 100, 2),
        'Precision': round(prec * 100, 2),
        'Recall'   : round(rec * 100, 2),
        'F1-Score' : round(f1 * 100, 2),
        'AUC-ROC'  : round(auc * 100, 2) if auc else 'N/A'
    })

    print(f"Accuracy : {acc:.4f}")
    print(f"F1-Score : {f1:.4f}")
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred,
                                target_names=['Real', 'Fake']))

# STEP 7: Summary table
results_df = pd.DataFrame(results)
print("\n" + "="*65)
print("SUMMARY - Traditional ML Models")
print("="*65)
print(results_df.to_string(index=False))

# STEP 8: Visualizations

# --- Accuracy bar chart ---
plt.figure(figsize=(10, 5))
colors = ['#4C72B0','#DD8452','#55A868','#C44E52','#8172B2','#937860']
bars = plt.bar(results_df['Model'], results_df['Accuracy'], color=colors)
plt.title('Accuracy Comparison — Traditional ML Models',
          fontsize=13, fontweight='bold')
plt.ylabel('Accuracy (%)')
plt.xticks(rotation=20, ha='right')
plt.ylim(0, 110)
for bar in bars:
    plt.text(bar.get_x() + bar.get_width()/2,
             bar.get_height() + 0.5,
             f"{bar.get_height():.1f}%",
             ha='center', fontsize=9)
plt.tight_layout()
plt.savefig('accuracy_comparison.png', dpi=150)
plt.show()

# --- Multi-metric grouped bar chart ---
metrics = ['Accuracy', 'Precision', 'Recall', 'F1-Score']
x = np.arange(len(results_df['Model']))
width = 0.18

fig, ax = plt.subplots(figsize=(14, 6))
metric_colors = ['#4C72B0', '#DD8452', '#55A868', '#C44E52']
for i, (metric, color) in enumerate(zip(metrics, metric_colors)):
    vals = results_df[metric].astype(float)
    ax.bar(x + i * width, vals, width, label=metric, color=color)

ax.set_title('All Metrics — Traditional ML Models',
             fontsize=13, fontweight='bold')
ax.set_xticks(x + width * 1.5)
ax.set_xticklabels(results_df['Model'], rotation=20, ha='right')
ax.set_ylabel('Score (%)')
ax.set_ylim(0, 115)
ax.legend()
plt.tight_layout()
plt.savefig('all_metrics.png', dpi=150)
plt.show()

# --- Confusion matrix for best model ---
best_name  = results_df.loc[results_df['F1-Score'].idxmax(), 'Model']
best_model = models[best_name]
y_pred_best = best_model.predict(X_test)

cm = confusion_matrix(y_test, y_pred_best)
plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Real', 'Fake'],
            yticklabels=['Real', 'Fake'])
plt.title(f'Confusion Matrix — {best_name}',
          fontsize=12, fontweight='bold')
plt.ylabel('Actual')
plt.xlabel('Predicted')
plt.tight_layout()
plt.savefig('confusion_matrix.png', dpi=150)
plt.show()

print(f"\nBest Model: {best_name}")

# ============================================================
# TF-IDF Analysis
# ============================================================

from sklearn.feature_extraction.text import TfidfVectorizer
import scipy.sparse as sp

# Reload raw text for TF-IDF analysis
CSV_PATH = '/content/drive/MyDrive/comparative-analysis-main/datasetnew/'

train_df = pd.read_csv(CSV_PATH + 'train_binary.csv')
test_df  = pd.read_csv(CSV_PATH + 'test_binary.csv')
val_df   = pd.read_csv(CSV_PATH + 'val_binary.csv')

# ── What TF-IDF does ────────────────────────────────────────
# TF  (Term Frequency)     = how often a word appears in ONE article
# IDF (Inverse Doc Freq)   = penalizes words that appear in ALL articles
# TF-IDF = TF × IDF → gives high score to words unique to that article

# ── Fit TF-IDF on training text ─────────────────────────────
tfidf = TfidfVectorizer(
    max_features = 14643,   # match your .npz shape exactly
    ngram_range  = (1, 2),  # unigrams + bigrams
    sublinear_tf = True,    # apply log(1+tf) smoothing
    min_df       = 2        # ignore words appearing in < 2 docs
)

X_train_text = train_df['statement'].astype(str)
X_test_text  = test_df['statement'].astype(str)

X_tfidf_train = tfidf.fit_transform(X_train_text)
X_tfidf_test  = tfidf.transform(X_test_text)

print("TF-IDF Matrix Info:")
print(f"  Training matrix shape : {X_tfidf_train.shape}")
print(f"  Test matrix shape     : {X_tfidf_test.shape}")
print(f"  Total features (words): {len(tfidf.get_feature_names_out())}")
print(f"  Matrix density        : {X_tfidf_train.nnz / (X_tfidf_train.shape[0] * X_tfidf_train.shape[1]):.4f}")
print(f"  (Very low density = sparse matrix, most values are 0)")

# ── Top TF-IDF words overall ─────────────────────────────────
feature_names = tfidf.get_feature_names_out()
mean_tfidf    = np.asarray(X_tfidf_train.mean(axis=0)).flatten()
top_indices   = mean_tfidf.argsort()[-20:][::-1]

print("\nTop 20 most important words by TF-IDF score:")
print("-" * 40)
for i, idx in enumerate(top_indices):
    print(f"  {i+1:2}. {feature_names[idx]:<25} score: {mean_tfidf[idx]:.4f}")

# ── Top words for FAKE news vs REAL news ─────────────────────
y_train = train_df['label'].values

fake_indices = np.where(y_train == 1)[0]
real_indices = np.where(y_train == 0)[0]

fake_tfidf = np.asarray(X_tfidf_train[fake_indices].mean(axis=0)).flatten()
real_tfidf = np.asarray(X_tfidf_train[real_indices].mean(axis=0)).flatten()

top_fake = fake_tfidf.argsort()[-15:][::-1]
top_real = real_tfidf.argsort()[-15:][::-1]

print("\nTop 15 words in FAKE news:")
print("-" * 35)
for idx in top_fake:
    print(f"  {feature_names[idx]:<25} {fake_tfidf[idx]:.4f}")

print("\nTop 15 words in REAL news:")
print("-" * 35)
for idx in top_real:
    print(f"  {feature_names[idx]:<25} {real_tfidf[idx]:.4f}")

# ── Visualization: Top TF-IDF words ──────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# Fake news top words
fake_words  = [feature_names[i] for i in top_fake]
fake_scores = [fake_tfidf[i] for i in top_fake]
axes[0].barh(fake_words[::-1], fake_scores[::-1], color='#C44E52')
axes[0].set_title('Top 15 TF-IDF Words — FAKE News',
                  fontsize=12, fontweight='bold')
axes[0].set_xlabel('Mean TF-IDF Score')

# Real news top words
real_words  = [feature_names[i] for i in top_real]
real_scores = [real_tfidf[i] for i in top_real]
axes[1].barh(real_words[::-1], real_scores[::-1], color='#4C72B0')
axes[1].set_title('Top 15 TF-IDF Words — REAL News',
                  fontsize=12, fontweight='bold')
axes[1].set_xlabel('Mean TF-IDF Score')

plt.tight_layout()
plt.savefig('tfidf_top_words.png', dpi=150)
plt.show()

# ── TF-IDF score distribution plot ───────────────────────────
sample_scores = np.asarray(
    X_tfidf_train[0].todense()).flatten()
nonzero_scores = sample_scores[sample_scores > 0]

plt.figure(figsize=(8, 4))
plt.hist(nonzero_scores, bins=30, color='#55A868', edgecolor='black')
plt.title('TF-IDF Score Distribution (Sample Article)',
          fontsize=12, fontweight='bold')
plt.xlabel('TF-IDF Score')
plt.ylabel('Word Count')
plt.tight_layout()
plt.savefig('tfidf_distribution.png', dpi=150)
plt.show()

print("\nTF-IDF Analysis complete!")
print("These charts go into Section 3 (Data Preprocessing) of your paper.")

# ============================================================
# FNDS - Fake News Detection Utility Score
# New cell - run after your existing results
# ============================================================

import time

# Step 1: Re-run models with timing measurement
timed_results = []

for name, model in models.items():
    print(f"Timing: {name}...")

    # Measure training time
    start_train = time.time()
    model.fit(X_train, y_train)
    train_time = time.time() - start_train

    # Measure inference time
    start_infer = time.time()
    y_pred = model.predict(X_test)
    infer_time = time.time() - start_infer

    # Metrics
    f1  = f1_score(y_test, y_pred, average='weighted', zero_division=0)

    try:
        if hasattr(model, 'predict_proba'):
            y_prob = model.predict_proba(X_test)[:, 1]
        else:
            y_prob = model.decision_function(X_test)
        auc = roc_auc_score(y_test, y_prob)
    except:
        auc = 0.0

    timed_results.append({
        'Model'       : name,
        'F1'          : round(f1, 4),
        'AUC'         : round(auc, 4),
        'Train_Time_s': round(train_time, 4),
        'Infer_Time_s': round(infer_time, 4)
    })

    print(f"  Train time : {train_time:.4f}s")
    print(f"  Infer time : {infer_time:.4f}s")

timed_df = pd.DataFrame(timed_results)
print("\nTiming Results:")
print(timed_df.to_string(index=False))

# Step 2: Calculate FNDS
# Formula: FNDS = α × F1 + β × AUC + γ × (1 - Normalized_Train_Cost)
# Weights: α=0.5, β=0.3, γ=0.2

alpha = 0.5   # F1 weight      - most important (classification balance)
beta  = 0.3   # AUC weight     - discrimination ability
gamma = 0.2   # Cost weight    - rewards faster/cheaper models

# Normalize training time (0 to 1 scale)
max_train_time = timed_df['Train_Time_s'].max()
timed_df['Norm_Cost'] = timed_df['Train_Time_s'] / max_train_time

# Calculate FNDS
timed_df['FNDS'] = (
    alpha * timed_df['F1'] +
    beta  * timed_df['AUC'] +
    gamma * (1 - timed_df['Norm_Cost'])
)
timed_df['FNDS'] = timed_df['FNDS'].round(4)

print("\n" + "="*70)
print("FNDS - Fake News Detection Utility Score")
print(f"Formula: FNDS = {alpha}×F1 + {beta}×AUC + {gamma}×(1 - Norm_Cost)")
print("="*70)
print(timed_df[['Model','F1','AUC','Train_Time_s',
                 'Norm_Cost','FNDS']].to_string(index=False))

# Best model by FNDS
best_fnds = timed_df.loc[timed_df['FNDS'].idxmax(), 'Model']
best_acc  = timed_df.loc[timed_df['F1'].idxmax(), 'Model']
print(f"\nBest model by F1    : {best_acc}")
print(f"Best model by FNDS  : {best_fnds}")
print("(If different, cost-efficiency changes the ranking!)")

# Step 3: FNDS Visualization
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Left - F1 vs FNDS comparison
x = np.arange(len(timed_df['Model']))
width = 0.35

axes[0].bar(x - width/2, timed_df['F1'],  width,
            label='F1-Score', color='#4C72B0')
axes[0].bar(x + width/2, timed_df['FNDS'], width,
            label='FNDS', color='#DD8452')
axes[0].set_title('F1-Score vs FNDS Comparison',
                  fontsize=12, fontweight='bold')
axes[0].set_xticks(x)
axes[0].set_xticklabels(timed_df['Model'], rotation=20, ha='right')
axes[0].set_ylabel('Score')
axes[0].set_ylim(0, 0.9)
axes[0].legend()

# Right - Training time bar chart
axes[1].bar(timed_df['Model'], timed_df['Train_Time_s'],
            color=['#4C72B0','#DD8452','#55A868',
                   '#C44E52','#8172B2','#937860'])
axes[1].set_title('Training Time per Model (seconds)',
                  fontsize=12, fontweight='bold')
axes[1].set_xticklabels(timed_df['Model'], rotation=20, ha='right')
axes[1].set_ylabel('Time (seconds)')

plt.tight_layout()
plt.savefig('fnds_comparison.png', dpi=150)
plt.show()

print("\nFNDS chart saved!")

# Step 4: Final combined table (for your paper)
final_df = results_df.merge(
    timed_df[['Model','Train_Time_s','Infer_Time_s','FNDS']],
    on='Model'
)

print("\n" + "="*80)
print("COMPLETE RESULTS TABLE - For Research Paper Section 5")
print("="*80)
print(final_df.to_string(index=False))