# -*- coding: utf-8 -*-
"""reasearch_paper_nndl_data_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1moAKYzbsSWHQYhTvHwdpN2-PWUz5ZURH
"""

pip install datasets pandas scikit-learn transformers torch

import pandas as pd

cols = ["id", "label", "statement", "subject", "speaker",
        "job", "state", "party", "barely_true", "false",
        "half_true", "mostly_true", "pants_fire", "context"]

train_df = pd.read_csv("/content/train.tsv", sep="\t", header=None, names=cols)
val_df   = pd.read_csv("/content/valid.tsv", sep="\t", header=None, names=cols)
test_df  = pd.read_csv("/content/test.tsv",  sep="\t", header=None, names=cols)

print("Train size:", len(train_df))
print("Val size:  ", len(val_df))
print("Test size: ", len(test_df))
print("\nOriginal labels:", train_df["label"].unique())

import pandas as pd
train_df=pd.read_csv('/content/train_binary.csv')
test_df=pd.read_csv('/content/test_binary.csv')
val_df=pd.read_csv('/content/val_binary.csv')

"""binary conversion

"""

#binary conversion
def convert_to_binary(label):
    if label in ["pants-fire", "false", "barely-true"]:
        return 0  # FAKE
    else:
        return 1  # REAL

train_df["binary_label"] = train_df["label"].apply(convert_to_binary)
val_df["binary_label"]   = val_df["label"].apply(convert_to_binary)
test_df["binary_label"]  = test_df["label"].apply(convert_to_binary)

print("Label distribution (train):")
print(train_df["binary_label"].value_counts())
print("\n0 = FAKE,  1 = REAL")

X_train = train_df["statement"].tolist()
y_train = train_df["binary_label"].tolist()

X_val   = val_df["statement"].tolist()
y_val   = val_df["binary_label"].tolist()

X_test  = test_df["statement"].tolist()
y_test  = test_df["binary_label"].tolist()

print("Total training samples:", len(X_train))
print("Sample statement:", X_train[0])
print("Binary label:    ", y_train[0])

import pickle
import pandas as pd

# ── Save as pickle (fastest to reload) ───────────────────────
with open("liar_binary.pkl", "wb") as f:
    pickle.dump({
        "X_train": X_train, "y_train": y_train,
        "X_val":   X_val,   "y_val":   y_val,
        "X_test":  X_test,  "y_test":  y_test
    }, f)
print("Saved as liar_binary.pkl")

# ── Also save as CSV (easy to inspect) ───────────────────────
pd.DataFrame({"statement": X_train, "label": y_train}).to_csv("train_binary.csv", index=False)
pd.DataFrame({"statement": X_val,   "label": y_val}).to_csv("val_binary.csv",   index=False)
pd.DataFrame({"statement": X_test,  "label": y_test}).to_csv("test_binary.csv",  index=False)
print("Saved as CSV files")

# ── Download all files to your PC ────────────────────────────
from google.colab import files
files.download("liar_binary.pkl")
files.download("train_binary.csv")
files.download("val_binary.csv")
files.download("test_binary.csv")
print("All files downloaded to your PC!")

"""Handling missing values"""

import pandas as pd
train_df=pd.read_csv('/content/train_binary.csv')
test_df=pd.read_csv('/content/test_binary.csv')
val_df=pd.read_csv('/content/val_binary.csv')
# Check for missing values
print("=== Missing Values ===")
print(train_df.isnull().sum())
print("\n=== Sample raw statements ===")
print(train_df[["label", "statement"]].head(10))
print("\n=== Label distribution ===")
print(train_df["label"].value_counts())

# Drop rows where statement is missing
train_df = train_df.dropna(subset=["statement"])
val_df   = val_df.dropna(subset=["statement"])
test_df  = test_df.dropna(subset=["statement"])

# Fill any remaining NaN with empty string
train_df["statement"] = train_df["statement"].fillna("")
val_df["statement"]   = val_df["statement"].fillna("")
test_df["statement"]  = test_df["statement"].fillna("")

print("After cleaning:")
print("Train:", len(train_df))
print("Val:  ", len(val_df))
print("Test: ", len(test_df))

#cleaning for if-idf
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer

nltk.download("stopwords")
stop_words = set(stopwords.words("english"))
stemmer = PorterStemmer()

# ── Full pipeline for traditional ML ─────────────────────────
def preprocess_traditional(text):
    text = str(text).lower()                        # Step 1: lowercase
    text = re.sub(r"http\S+|www\S+", "", text)      # Step 2: remove URLs
    text = re.sub(r"[^a-zA-Z\s]", "", text)         # Step 3: remove special chars
    text = re.sub(r"\s+", " ", text).strip()         # Step 4: remove extra spaces
    tokens = text.split()
    tokens = [w for w in tokens if w not in stop_words]  # Step 5: stopwords
    tokens = [stemmer.stem(w) for w in tokens]           # Step 6: stemming
    return " ".join(tokens)

# Apply to all splits
X_train_clean = [preprocess_traditional(t) for t in X_train]
X_val_clean   = [preprocess_traditional(t) for t in X_val]
X_test_clean  = [preprocess_traditional(t) for t in X_test]

# ── TF-IDF vectorization ──────────────────────────────────────
tfidf = TfidfVectorizer(
    max_features  = 50000,
    ngram_range   = (1, 2),
    sublinear_tf  = True,
    min_df        = 2
)

X_train_tfidf = tfidf.fit_transform(X_train_clean)  # fit ONLY on train
X_val_tfidf   = tfidf.transform(X_val_clean)
X_test_tfidf  = tfidf.transform(X_test_clean)

print("=== Preprocessing Complete ===")
print("TF-IDF shape:", X_train_tfidf.shape)
print("\nSample original :", X_train[0])
print("Sample cleaned  :", X_train_clean[0])

"""For transformer cleaning"""

# ── Minimal pipeline for transformers ────────────────────────
def preprocess_transformer(text):
    text = str(text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

X_train_trans = [preprocess_transformer(t) for t in X_train]
X_val_trans   = [preprocess_transformer(t) for t in X_val]
X_test_trans  = [preprocess_transformer(t) for t in X_test]

print("Transformer preprocessing complete")
print("Sample:", X_train_trans[0])

"""Downloading files"""

# Save + Download TF-IDF matrices (ONLY these three)

from scipy.sparse import save_npz
from google.colab import files

# ── Save files ─────────────────────────────
save_npz("X_train_tfidf.npz", X_train_tfidf)
save_npz("X_val_tfidf.npz", X_val_tfidf)
save_npz("X_test_tfidf.npz", X_test_tfidf)

print("Files saved successfully!")

# ── Download files ─────────────────────────
files.download("X_train_tfidf.npz")
files.download("X_val_tfidf.npz")
files.download("X_test_tfidf.npz")

# Save + Download transformer preprocessed data

import pandas as pd
from google.colab import files
import zipfile

# ── Save as CSV ────────────────────────────
pd.DataFrame(X_train_trans, columns=["text"]).to_csv("X_train_trans.csv", index=False)
pd.DataFrame(X_val_trans, columns=["text"]).to_csv("X_val_trans.csv", index=False)
pd.DataFrame(X_test_trans, columns=["text"]).to_csv("X_test_trans.csv", index=False)

print("Files saved successfully!")

# ── Zip files (optional but recommended) ───
with zipfile.ZipFile("transformer_data.zip", "w") as z:
    z.write("X_train_trans.csv")
    z.write("X_val_trans.csv")
    z.write("X_test_trans.csv")

# ── Download ──────────────────────────────
files.download("transformer_data.zip")

